### ISSUE TITLE
Add support for OAuth2

### ISSUE THREAD

**Issue by cpbl** [realpine/alpine#32]
I am hoping that the title of this issue is enough to convey the whole point, to those who understand.
My university just imposed OAuth2 (two-factor authentication) via Microsoft on me in order to use my professional email address ! ! 
And Alpine no longer works to send my email.

**Comment by jrbinks** [comment]
Dead project.  "In August 2013, the re-alpine project official announced the December 21, 2012, release of Re-alpine 2.03, their last official release"

See now https://repo.or.cz/alpine.git instead, where there is some OAuth2 support (https://alpine.x10host.com/alpine/alpine-info/misc/SettingXOAUTH2Outlook.html)

**Comment by cpbl** [comment]
Yes, thank you. 
The latter doesn't work for me, as I've posted on https://stackoverflow.com/questions/64578801/alpine-email-client-with-two-factor-authentication-to-microsoft-hosted-email-ser
