### ISSUE TITLE
Store password for IMAP server

### ISSUE THREAD

**Issue by joshuamoorexyz** [realpine/alpine#33]
I have followed every trace of a guide on the internet to be able to save my password in hopes that i dont have to type it everytime i want to go in my Inbox or send an email as my password is very long.Am i missing something or can someone please help me achieve this?Thank you

**Comment by geofft** [comment]
This particular fork of alpine isn't active any more, I think you'll want to ask whoever is providing alpine to you. (The one I run seems to support passwords in .netrc files.)
